name: ditto_train
channels:
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=41.0.7=py310hdda0065_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dataclasses=0.8=pyhc8e2a94_3
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - iopath=0.1.9=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.2=py310h5f9d8c6_0
  - numpy-base=1.26.2=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - pandas=2.1.1=py310h1128e8f_0
  - portalocker=2.8.2=py310hff52083_1
  - portaudio=19.6.0=h7b6447c_4
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.5=py310_cu113_pyt1121
  - pytz=2023.3.post1=py310h06a4308_0
  - pyyaml=6.0=py310h5764c6d_4
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - setuptools=68.0.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py310_cu113
  - tqdm=4.66.1=pyhd8ed1ab_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py310h06a4308_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.33.0
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - attrs==23.1.0
      - audioread==3.0.1
      - av==11.0.0
      - cachetools==5.3.2
      - chumpy==0.70
      - coloredlogs==15.0.1
      - configargparse==1.7
      - contourpy==1.2.0
      - crcmod==1.7
      - cycler==0.12.1
      - dearpygui==1.10.1
      - decorator==4.4.2
      - dill==0.3.8
      - docstring-parser==0.16
      - einops==0.7.0
      - face-alignment==1.4.1
      - facenet-pytorch==2.6.0
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.46.0
      - fsspec==2023.12.1
      - google-auth==2.25.2
      - google-auth-oauthlib==1.1.0
      - grpcio==1.60.0
      - hsemotion==0.3.0
      - huggingface-hub==0.24.5
      - humanfriendly==10.0
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - kornia==0.7.0
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.41.1
      - lpips==0.1.4
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mediapipe==0.10.8
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multiprocess==0.70.16
      - natsort==8.4.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numba==0.58.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - onnx==1.16.2
      - onnxruntime-gpu==1.16.3
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.8.1.78
      - oss2==2.18.3
      - packaging==23.2
      - pillow==10.2.0
      - pip==24.0
      - platformdirs==4.1.0
      - pooch==1.8.0
      - praat-parselmouth==0.4.3
      - proglog==0.1.10
      - protobuf==3.20.3
      - psutil==6.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyaudio==0.2.11
      - pycryptodome==3.19.0
      - pygments==2.17.2
      - pykalman==0.9.7
      - pymcubes==0.1.4
      - pyparsing==3.1.1
      - python-speech-features==0.6
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rich==13.7.0
      - rsa==4.9
      - safetensors==0.4.1
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scikit-video==1.1.11
      - scipy==1.11.4
      - shtab==1.7.1
      - sounddevice==0.4.6
      - soundfile==0.12.1
      - soxr==0.3.7
      - sympy==1.13.2
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - tifffile==2023.12.9
      - timm==0.9.0
      - tokenizers==0.15.0
      - torch==2.2.2
      - torch-ema==0.3
      - torchvision==0.17.2
      - transformers==4.36.0
      - trimesh==4.0.5
      - triton==2.2.0
      - typing-extensions==4.15.0
      - tyro==0.8.8
      - werkzeug==3.0.1
prefix: /opt/conda/envs/ditto_train
